#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi


zstyle ':prezto:load' pmodule \
  'environment' \
  'terminal' \
  'rust' \
  'cargo' \
  'editor' \
  'history' \
  'directory' \
  'spectrum' \
  'utility' \
  'completion' \
  'prompt' \
  'git' \
  'history-substring-search' \
  'syntax-highlighting' \
  'ssh' \
  'rsync'



# Customize to your needs...
# export PATH="/home/jean/miniconda3/bin:$PATH"  # commented out by conda initialize

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/jean/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/jean/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/home/jean/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/jean/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

export PATH="${PATH}:${HOME}/.cargo/bin"

